version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: fluxid
    main: ./cmd/fluxid
    binary: fluxid
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X fluxid-cli/internal/version.Version={{.Version}}
      - -X fluxid-cli/internal/version.GitCommit={{.Commit}}
      - -X fluxid-cli/internal/version.BuildDate={{.Date}}

archives:
  - id: default

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

snapshot:
  version_template: "{{ incpatch .Version }}-next"
